DROP TABLE IF EXISTS CONFIG; 
CREATE TABLE CONFIG(
    CONFIG_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    CONFIG_NAME VARCHAR(255),
    DATASOURCE_ID VARCHAR(255)
);   
      

DROP TABLE IF EXISTS DATASOURCE; 
CREATE TABLE DATASOURCE(
    DATASOURCE_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    DATASOURCE_NAME VARCHAR(255),
    JDBC_DRIVER VARCHAR(255),
    JDBC_PASSWORD VARCHAR(255),
    JDBC_URL VARCHAR(255),
    JDBC_USER_NAME VARCHAR(255)
);          
             

DROP TABLE IF EXISTS TEMPLATE; 
CREATE TABLE TEMPLATE(
    TEMPLATE_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    CONFIG_ID VARCHAR(255),
    TEMPLATE_NAME VARCHAR(255),
    TEMPLATE_TYPE VARCHAR(255),
    GENERATE_BASE_PACKAGE_PATH VARCHAR(255),
    GENERATE_PACKAGE_PATH VARCHAR(255),
    GENERATE_SOURCE_FOLDER VARCHAR(255),
    GENERATE_SUFFIX VARCHAR(255),
    TEMPLATE_CONTENT VARCHAR(20000)
);    
             
